spring:
  thymeleaf:
    prefix: classpath:/static/
    check-template-location: true
    cache: false
    suffix: .html
    encoding: UTF-8
    content-type: text/html; charset=utf-8
    mode: HTML5
  application:
    name: wechat
  datasource:
    url: jdbc:mysql://localhost:3306/wechat?useSSL=false&useUnicode=true&characterEncoding=utf8
    username: root
    password: XinHong12345
    driver-class-name: com.mysql.jdbc.Driver
eureka:
  instance:
    prefer-ip-address: true #以IP地址注册到服务中心
    hostname: ${spring.cloud.client.ipAddress}
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://test:test@localhost:9091/eureka/
server:
  port: 80
  #ssl:
    #key-store: server.keystore
    #key-alias: tomcat
    #enabled: true
    #key-store-password: 123456
    #key-store-type: JKS
security:
  user:
    name: test
    password: test
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  #pattern:
  #格式化，只能输出日期和内容
  #console: "%d - %msg%n"
  path: /usr/logs
  file: /usr/logs/wechat.log
